services:
  App\CatalogBundle\Decorators\DecoratingTwig:
    decorates: twig
    decoration_inner_name: twig.inner
    arguments: ['@twig.inner']
    autowire: false

#  app.twig.extension:
#    class: App\CatalogBundle\Twig\Catalog_Twig_Extension
#    tags:
#    -  { name: twig.extension }