#index:
#    path: /
#    controller: App\Controller\DefaultController::index

catalog_bundle:
  # loads routes from the YAML or XML files found in some bundle directory
  resource: '@CatalogBundle/Controller/'
  type:     annotation

api_catalog_bundle:
  # loads routes from the YAML or XML files found in some bundle directory
  resource: '@CatalogBundle/ApiController/'
  type:     annotation

api_login_check:
  path: /api/login_check